## Amiga 500 for MEGA65 (AExp)
##
## Core specific constraints
##
## This machine is based on Minimig-AGA_MiSTer (MiSTer-devel/Minimig-AGA_MiSTer)
## Powered by MiSTer2MEGA65
## MEGA65 port done in 2026 and licensed under GPL v3


## Name Autogenerated Clocks
## Important: Using them in subsequent statements, e.g. clock dividers requires that they
## have been named/defined here before
## otherwise Vivado does not find the pins)
##
## main_clk is the Amiga's core clock (PAL 28.37516 MHz, -5.6 ppm). Everything in the core
## runs on it; the 7.09 MHz bus timing is made of clock enables (amiga_clk.v), and
## cpu_wrapper.v contains a (pruned with cpucfg=00) negedge-clk FSM - both edges of main_clk
## are therefore timed automatically.
##
## HDMI flicker-free (issue #12): clk.vhd generates two core clocks - "native" 28.375000 MHz
## (i_clk_main) and the flicker-free "fast" twin 28.437500 MHz (i_clk_fast) - and a
## BUFGMUX_CTRL selects between them from hr_core_speed(0) (the FSM in mega65.vhd). We time
## the SHORTEST-period leg for worst-case setup: set_case_analysis 1 freezes the select on
## the fast leg, and main_clk is defined on i_clk_fast/CLKOUT0. That single generated clock
## constant-propagates the native leg off the net, so no set_clock_groups is needed (the
## C64MEGA65 pattern, with the twin direction mirrored: our twin is faster, not slower).
##
## PIN-NAME DISCIPLINE (load-bearing): if either get_pins matches nothing (instance renamed,
## or the select FF merged/retimed away), Vivado only WARNS ("no pins matched") and the
## constraint silently no-ops - an empty set_case_analysis re-introduces phantom
## native<->fast inter-clock paths, and main_clk becomes undefined. Keep the leaf names
## i_clk_fast (clk.vhd) and hr_core_speed (mega65.vhd). Post-synth sign-off gate: BOTH
## get_pins must return non-empty, and the routed report must show main_clk at ~35.165 ns
## (the fast period), not 35.242 ns.
## Megamiga: the SDRAM controller's 113.5 MHz clock comes from the NATIVE MMCM (CLKOUT1) and
## mega65.vhd ties the mux select to native, so the core clock is the native leg and is timed
## as such: main_clk on i_clk_main/CLKOUT0, the select frozen at 0. The 4x clock keeps its
## auto-derived name and is synchronous to main_clk (same MMCM), so the 28 <-> 113.5 MHz
## crossings in amiga_sdram.vhd are timed as ordinary synchronous paths.
## (AExp timed the flicker-free fast leg here: set_case_analysis 1 on hr_core_speed_reg[0]/Q
## and main_clk on i_clk_fast/CLKOUT0.)
set_case_analysis 0 [get_pins CORE/clk_gen/i_bufgmux/S]
create_generated_clock -name main_clk [get_pins CORE/clk_gen/i_clk_main/CLKOUT0]
# Add more clocks here, if needed

## ascal asynchronous FIFO data crossings (framework paths, constrained here
## because M2M/common.xdc must not be modified - candidate for upstreaming).
##
## ascal's input and output double buffers (i_dpram/o_dpram, explicitly kept
## in LUTRAM with ram_style="distributed") are ping-pong CDC FIFOs: i_dpram
## is written on i_clk (= main_clk) and read on avl_clk (= hr_clk); o_dpram is
## written on avl_clk and read on o_clk (= hdmi_clk). The handshake registers
## are already cut by the false_path patterns in M2M/common.xdc:113-117, but
## those match only register /C pins. The LUTRAM primitives launch from their
## /CLK pins and were therefore timed at the worst-case edge alignment of
## unrelated MMCM outputs (44 ps / 34 ps requirements, impossible by
## construction). Worse, the router inserted large hold-fix detours on these
## paths, which polluted the genuine intra-hr_clk setup paths (first R3 run:
## WNS -6.7 ns).
##
## set_max_delay -datapath_only bounds the data staleness to one destination
## clock period and removes the hold analysis (and with it the detours).
set_max_delay -datapath_only 10.000 \
   -from [get_pins -hierarchical -regexp {.*/i_ascal/i_dpram_reg.*/CLK}] \
   -to   [get_cells -hierarchical -regexp {.*/i_ascal/avl_dr_reg\[[0-9]+\]}]
set_max_delay -datapath_only 13.400 \
   -from [get_pins -hierarchical -regexp {.*/i_ascal/o_dpram_reg.*/CLK}] \
   -to   [get_cells -hierarchical -regexp {.*/i_ascal/o_dr_reg\[[0-9]+\]}]

## Hardware Floppy: qnice_clk <-> main_clk CDC (WIP-V2-A2)
##
## The physical-floppy read front-end (physical_fdd_top, 50 MHz qnice_clk)
## introduced the first RAW synchronizer crossings between qnice_clk and
## main_clk: the Cummings word FIFO (Gray-pointer 2-FF syncs both ways plus
## the LUTRAM read data into adf_track_engine's io_din register), and the
## control-context/dsksync 2-FF metas (en/sel/mot_meta, sync_meta). All
## earlier qnice<->main traffic went through cdc_stable (bounded by
## M2M/common.xdc) or dual-clock BRAM, so these two MMCM-unrelated clocks
## had never exposed an unconstrained fabric path - the first R3 build
## timed them at worst-case edge alignment: WNS -6.331, 47 endpoints, ALL
## of them inside this plumbing (the exact failure class of C64MEGA65's
## physical-1581 first build).
##
## Every crossing is a 2-FF synchronizer (async_reg-tagged), a Gray-coded
## pointer, or the FIFO data path whose stability the Gray protocol
## guarantees (data settles >= 2 destination periods before the synced
## pointer exposes it). A clock-pair set_max_delay -datapath_only of one
## qnice period bounds the staleness/skew of all of them and removes the
## hold-fix detours. DELIBERATELY max_delay and not the C64's blanket
## set_false_path: object-scoped exceptions of the same type stay in force
## (common.xdc's cdc_stable set_max_delay keeps its tighter bound), while a
## clock-pair false path would OVERRIDE those bounds (false path outranks
## max delay regardless of specificity).
set_max_delay -datapath_only 20.000 \
   -from [get_clocks qnice_clk] -to [get_clocks main_clk]
set_max_delay -datapath_only 20.000 \
   -from [get_clocks main_clk] -to [get_clocks qnice_clk]

## Notes for timing review after the first synthesis (do not enable blindly):
## - rtl/minimig_m68k_bridge.v uses a logic signal (_as_and_cs) as an async
##   preset (infers FDPE) - check the timing report for it.
## - rtl/paula_floppy.v has 'posedge clk or negedge IO_ENA' blocks. Since the
##   ADF floppy milestone, IO_ENA (= IO_FPGA) is LIVE: it is driven by a
##   plain main_clk register in adf_track_engine.vhd (io_fpga_o, no
##   combinational gating), so the async CLR pins get same-clock
##   recovery/removal checks that Vivado analyzes automatically - verify
##   them in the timing report of every build.
## - SDRAM (Megamiga, CORE/vhdl/amiga_sdram.vhd + Minimig rtl/sdram_ctrl.v): Chip, Slow,
##   Kickstart and Fast RAM. The controller runs at 113.5 MHz (4 x main_clk, same MMCM) and
##   generates the SDRAM clock as a REGISTER output (56.75 MHz): command/address/data change
##   one 113.5 MHz period before the SDRAM clock rises and are held one period after, and read
##   data is sampled one period after the edge it was launched with - the MiSTer scheme. This
##   only holds with ALL pin registers in the IOBs (matched clock-to-out), hence IOB TRUE
##   below; there are no set_input/output_delay constraints. After implementation, check the
##   ILOGIC/OLOGIC counts and the absence of IOB-packing warnings for the SDRAM ports.

## Megamiga: SDRAM pin registers in the IOBs (see the note above)
set_property IOB TRUE [get_ports {sdram_a_o[*] sdram_ba_o[*] sdram_ras_n_o sdram_cas_n_o sdram_we_n_o sdram_dqml_o sdram_dqmh_o sdram_clk_o sdram_dq_io[*]}]

## Megamiga: minimig -> SDRAM controller, 2 cycles of the 113.5 MHz clock (MiSTer's
## Minimig.sdc does the same: "-from minimig -to ram1 -setup 2 / -hold 1"). A minimig signal
## only changes on the core clock edge that starts a 7 MHz cycle (c1 rising); sdram_ctrl
## detects that edge one fast clock later (old_7m) and samples the chipset address, data and
## strobes in state 0, at the SECOND fast clock edge after the launch. The cache snoop uses
## them even later. The maintenance writer (amiga_sdram.vhd) is NOT covered: it stays
## single-cycle timed, so the controller can never sample a half-settled address from it. Two more sources feed the same chipset nets: the cck register of
## amiga_clk (like MiSTer's sdc) and the framework's qnice2main OSM bits, which reach the
## chip write data through Paula's floppy muxes (Hardware Floppy unit mapping) - menu
## settings that are static while the Amiga runs.
set_multicycle_path -setup 2 -from [get_cells -hierarchical -filter {IS_PRIMITIVE && (NAME =~ CORE/i_main/i_minimig/minimig_inst/* || NAME =~ CORE/i_main/i_amiga_clk/cck* || NAME =~ i_framework/i_qnice2main/*)}] -to [get_cells -hierarchical -filter {IS_PRIMITIVE && NAME =~ CORE/i_amiga_sdram/i_sdram_ctrl/*}]
set_multicycle_path -hold 1 -from [get_cells -hierarchical -filter {IS_PRIMITIVE && (NAME =~ CORE/i_main/i_minimig/minimig_inst/* || NAME =~ CORE/i_main/i_amiga_clk/cck* || NAME =~ i_framework/i_qnice2main/*)}] -to [get_cells -hierarchical -filter {IS_PRIMITIVE && NAME =~ CORE/i_amiga_sdram/i_sdram_ctrl/*}]

## Megamiga RTG (M2M-UPSTREAM rtg-framebuffer): MiSTer's RTG registers (CORE/i_main/i_rtg, core
## clock) drive ascal's framebuffer-mode inputs (o_fb_ena/hsize/vsize/format/base/stride), which
## ascal samples asynchronously in its Avalon (hr_clk) and output (hdmi_clk) domains. They only
## change when the Picasso96 driver switches a mode; a torn value lasts one frame at most. The
## palette writes stay timed: ascal's pal2 RAM is written on the core clock (fb_pal_clk).
set_false_path -from [get_cells -hierarchical -filter {IS_SEQUENTIAL && NAME =~ CORE/i_main/i_rtg/*}] -to [get_clocks {hr_clk hdmi_clk}]

## Megamiga: CPU -> SDRAM controller, 2 cycles of the 113.5 MHz clock - the other half of MiSTer's
## Minimig.sdc ("-from cpu_wrapper|cpu_inst* -to ram* -setup 2 / -hold 1"; MiSTer runs the CPU at
## 28 MHz and the controller at 114 MHz too). The CPU's address, data and strobes change on a
## core clock edge; the controller only acts on them through cpuCS = amiga_sdram's ram_cs, a
## 113.5 MHz register that samples the select at the FIRST fast edge after the core edge (that
## path stays single-cycle timed: amiga_sdram is not in the -to list), so the write buffer, the
## cache and the slot logic use them from the SECOND fast edge on. Until 0.4.0 this path was left
## single-cycle; with the 68020 address adder (TG68K register file -> sd_ba) it had shrunk to
## +0.001 ns.
set_multicycle_path -setup 2 -from [get_cells -hierarchical -filter {IS_PRIMITIVE && (NAME =~ CORE/i_main/i_cpu_wrapper/cpu_inst_p/* || NAME =~ CORE/i_main/i_cpu_wrapper/cpu_inst_o/*)}] -to [get_cells -hierarchical -filter {IS_PRIMITIVE && NAME =~ CORE/i_amiga_sdram/i_sdram_ctrl/*}]
set_multicycle_path -hold 1 -from [get_cells -hierarchical -filter {IS_PRIMITIVE && (NAME =~ CORE/i_main/i_cpu_wrapper/cpu_inst_p/* || NAME =~ CORE/i_main/i_cpu_wrapper/cpu_inst_o/*)}] -to [get_cells -hierarchical -filter {IS_PRIMITIVE && NAME =~ CORE/i_amiga_sdram/i_sdram_ctrl/*}]

## Megamiga RTG blitter (rtg_blitter.vhd): the registers are written on the core clock and read by
## the engine on hr_clk only while a command runs (the driver does not touch them until busy is
## clear), so their paths only need a sane bound. The start/done toggles are 2-FF synchronised
## (ASYNC_REG) and get one hr_clk period.
set_max_delay -datapath_only -from [get_cells -hierarchical -filter {IS_SEQUENTIAL && NAME =~ CORE/i_rtg_blitter/m_par_*}] -to [get_clocks hr_clk] 20.000
set_max_delay -datapath_only -from [get_cells -hierarchical -filter {IS_SEQUENTIAL && NAME =~ CORE/i_rtg_blitter/m_req_reg*}] -to [get_cells -hierarchical -filter {NAME =~ CORE/i_rtg_blitter/h_req_meta_reg*}] 10.000
set_max_delay -datapath_only -from [get_cells -hierarchical -filter {IS_SEQUENTIAL && NAME =~ CORE/i_rtg_blitter/h_ack_reg*}] -to [get_cells -hierarchical -filter {NAME =~ CORE/i_rtg_blitter/m_ack_meta_reg*}] 10.000
